### ISSUE TITLE
How to get the labels of a Pod

### ISSUE THREAD

**Issue by a11enhuang** [fabric8io/spring-cloud-kubernetes#108]
I use `spring-cloud-starter-kubernetes-fabric8` as the service discovery framework for gRPC, but when I try to get the instance, I can't get the Pod's labels. Examples are as follows:
```xml
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes-fabric8</artifactId>
    <version>2.1.1</version>
</dependency>
```

```java
List<ServiceInstance> instances = bean.getInstances("serviceName");
```
When I deploy multiple Pod instances, `ServiceInstance` only contains `labels` of `service`, but not `labels` of `Pod`.
I think it is necessary to get the `labels` of the `Pod`, because I may deploy multiple versions of the `Pod`, but only want to access a certain version of the `Pod`. I tried adding the version number to the `labels` of the `Pod`, but found that the `labels` of the `Pod` could not be obtained by the above method. Am I using the wrong method? Or is it that the `labels` of the `Pod` cannot be obtained yet?

**Comment by manusa** [comment]
Late reply, but just for the record, this project is no longer maintained.

It was forked and is actively maintained at: https://github.com/spring-cloud/spring-cloud-kubernetes
