### ISSUE TITLE
Cannot get ConfigMaps to work

### ISSUE THREAD

**Issue by cesartl** [fabric8io/spring-cloud-kubernetes#37]
I have a spring boot app called `hello-ribbon`

In my `bootstrap.properties`:

    spring.application.name=hello-ribbon
    foo.bar=dummy

In `k8s` I have a `hello-ribbon` config map:

    $ kubectl get configmaps hello-ribbon -o yaml

    apiVersion: v1
    data:
      foo.bar: newValue
    kind: ConfigMap
    metadata:
      creationTimestamp: 2016-07-13T16:05:07Z
      name: hello-ribbon
      namespace: default
      resourceVersion: "5839"
      selfLink: /api/v1/namespaces/default/configmaps/hello-ribbon
      did: 91a4881c-4913-11e6-964a-0621b591590f
 
When my app starts I can see in the logs:

    b.c.PropertySourceBootstrapConfiguration : Located property source: ConfigMapPropertySource [name='configmap.hello-ribbon.null']

In Java:

    @Value("${foo.bar}")
    private String fooBar;

I created a simple REST end point that returns `fooBar`.

The problem is that the value of `foo.bar` is always the value pulled from `bootstrap.properties`, never the value from the `kuberntes` `configMap`.

Am I missing something or this is a bug?

**Comment by iocanel** [comment]
Tbh I am not sure what should be the correct behavior here. I mean I am not sure if overriding the bootstrap property is the expected. I l'll have a look and I'll get back to you.

**Comment by cesartl** [comment]
ok thanks. Any idea what the `null` means in `configmap.hello-ribbon.null`?

**Comment by iocanel** [comment]
`configmap.hello-ribbon.null` is the name of the configmap property source. The null part is the namespace. The client interprets null namespace as the `current` namespace. Still it shouldn't appear as null in the config map property source name.

Can you try using this env var below inside your pod?

          env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"

It's possible that your pod can't find the namespace it belongs and thus can't see the config map.

**Comment by cesartl** [comment]
Brilliant that worked.

In the start log I can now see:

    Located property source: ConfigMapPropertySource [name='configmap.hello-ribbon.default']

And the value of `foo.bar` is overridden by the config map.

Should the documentation be updated?

**Comment by iocanel** [comment]
Definitely! I also intend to add a warning in the logs and expose the namespace in the health endpoint.

**Comment by christian-posta** [comment]
@cesartl if this is working for you, can you close this issue?
