### ISSUE TITLE
Synchronization issue

### ISSUE THREAD

**Issue by asm0dey** [fabric8io/spring-cloud-kubernetes#40]
I thank that here:
https://github.com/fabric8io/spring-cloud-kubernetes/blob/0a274621aadbd6c3ddef7c8f1a40c8460619ca19/spring-cloud-kubernetes-discovery/src/main/java/io/fabric8/spring/cloud/discovery/KubernetesDiscoveryLifecycle.java#L42
is some synchronization issue. Actions inside `if(!isRuning())` are not synchronized, so effectively code running is like that:
```java
if(!running) {
    getContext().publishEvent(new InstanceRegisteredEvent<>(this, getConfiguration()));
    running = true;
}
```
where running is just volatile boolean.

Any number of threads can see that `running == false` and then persorm actions inside if block.

**Comment by iocanel** [comment]
@asm0dey: Sorry, for the long delay, but I thought I that I had already responded!

I think too that you are right! I just sent a PR to address that.

**Comment by asm0dey** [comment]
I think that was minor bug, so NP

**Comment by christian-posta** [comment]
wanna close @asm0dey if this looks okay now?

**Comment by asm0dey** [comment]
@christian-posta looks perfectly fine
