### ISSUE TITLE
Dependencies in RC1

### ISSUE THREAD

**Issue by juan81** [fabric8io/spring-cloud-kubernetes#41]
Project depends on spring-cloud-sleuth-dependencies version RC1, this library already has an official release, so no need to depends on RC.

**Comment by christian-posta** [comment]
@juan81 think this PR fixes all of that https://github.com/fabric8io/spring-cloud-kubernetes/pull/47

Waiting for a new build 0.15 that should address this.

**Comment by christian-posta** [comment]
Should be resolved in this release https://github.com/fabric8io/spring-cloud-kubernetes/releases/tag/v0.0.15
