### ISSUE TITLE
What is the alternative if you don't use this project?

### ISSUE THREAD

**Issue by alberttwong** [fabric8io/spring-cloud-kubernetes#42]
I was curious what is the alternative?   Use ConfigMap to create the Spring Framework  application.properties file?

**Comment by iocanel** [comment]
Yeah, you could mount the configmap and treat it as a regular file.

In fact, many people will claim that its cleaner to do it that way. It's a matter of preference really.

**Comment by christian-posta** [comment]
+1 what @iocanel said.

Basically mount a configMap or gitVolume repo containing application.yml into $BASE/config where $BASE is where java -jar yourjar.jar is run. Spring Boot will then pick up the config from there (http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html) 

Additionally, you don't need the ribbon integration from this (spring-cloud) project. Can just use server-side service discovery with k8s services directly (http://blog.christianposta.com/microservices/netflix-oss-or-kubernetes-how-about-both/) . For more complex routing, you can use this project's ribbon or just use DiscoveryClient directly. Could even combine this with a Camel route to do more complex, domain-driven, routing.
