### ISSUE TITLE
UnknownHostException: kubernetes.default.svc

### ISSUE THREAD

**Issue by rblazquez** [fabric8io/spring-cloud-kubernetes#44]
Trying to work with DiscoveryClient i have:

1º @EnableDiscoveryClient

2º  @Autowired private DiscoveryClient discoveryClient;

3º List<ServiceInstance> instances = discoveryClient.getInstances(myServiceName);

However i get UnknownHostException: kubernetes.default.svc

Otherwise if i do not @EnableDiscoveryClient then i have no errors but i get always 0 instances. While i can see my service has 1 pod associated.

Can ou give me some hints?

**Comment by rblazquez** [comment]
I solved this passing an environment variable to the pod with the name of the kubernetes service.

name: KUBERNETES_MASTER
value: kubernetes

**Comment by jimmidyson** [comment]
Do you have the Kubernetes DNS addon deployed? It's a pretty essential part of any Kubernetes deployment nowadays so I'd recommend it if you don't.
