### ISSUE TITLE
Always get zero instances

### ISSUE THREAD

**Issue by rblazquez** [fabric8io/spring-cloud-kubernetes#45]
Trying to make discovery to work in my cluster i can see now that health check seems good:

"discoveryClient":{"description":"Kubernetes Discovery Client","status":"UP","services":["kubernetes","myService","kubernetes-dashboard"]}}

I also check that DiscoveryService is injected in the bean

@Autowired
private DiscoveryClient discoveryClient;

However when i 

List<ServiceInstance> instances = discoveryClient.getInstances("myService");

I get always zero instances ... when i can see that the service is working and there is a POD serving.

any idea how can i debug this?

**Comment by sundrio** [comment]
The most common issue, is the the pod not knowing the namespace it belongs. Have a look at the troubleshooting section in the readme at https://github.com/fabric8io/spring-cloud-kubernetes

**Comment by christian-posta** [comment]
@rblazquez does adding the namespace information help for this issue?
