### ISSUE TITLE
d-m-p and f-m-p in the mvn release profile?

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/spring-cloud-kubernetes#49]
Anyone know why we have d-m-p/f-m-p in this project? Doesn't seem to build any docker images or need to create kubernetes manifest files (it's a component library on top of spring-cloud). @rawlingsj @jstrachan @iocanel can anyone think why it's there? Is it tied some how to the way we do CI/CD with fabric8 when we try to do a build/release?

https://github.com/fabric8io/spring-cloud-kubernetes/blob/master/pom.xml#L431

**Comment by jstrachan** [comment]
Probably just a copy & paste ;)

**Comment by rawlingsj** [comment]
I was just typing the same response!

**Comment by christian-posta** [comment]
Cool thx.. will remove it

**Comment by christian-posta** [comment]
closed with https://github.com/fabric8io/spring-cloud-kubernetes/pull/51
