### ISSUE TITLE
DiscoveryClient returns only the first ServiceInstance

### ISSUE THREAD

**Issue by jfgosselin** [fabric8io/spring-cloud-kubernetes#54]
Tried the (version 0.0.16) on K8S v1.2.2 .  When try to get the list  of ServiceInstance it returns only the first one. I was expected to get all the endpoints for my service.

`     final List<ServiceInstance> services = discoveryClient.getInstances("myservice");
`

After some debugging in KubernetesDiscoveryClient it seems that .getSubsets() in  List<ServiceInstance> getInstances(String serviceId) returns a list with a single item : 

The output looked like this, all the EndpointAddress are under a single EndpointSubset.  Is it expected to work like this ?

`[EndpointSubset
(addresses=[
EndpointAddress(ip=172.17.19.25, targetRef=ObjectReference(apiVersion=null, fieldPath=null, kind=Pod, name=lcds-9a0c92bfe2c7fe9d584ed3d0a503808c-wi0qw, namespace=jfgosselin, resourceVersion=8523390, uid=ffb2f196-63df-11e6-8645-0050568e1a8a, additionalProperties={}), additionalProperties={}), 
EndpointAddress(ip=172.17.2.16, targetRef=ObjectReference(apiVersion=null, fieldPath=null, kind=Pod, name=lcds-9a0c92bfe2c7fe9d584ed3d0a503808c-i17dj, namespace=jfgosselin, resourceVersion=8069340, uid=ffb33b5e-63df-11e6-8645-0050568e1a8a, additionalProperties={}), additionalProperties={}), 
EndpointAddress(ip=172.17.28.7, targetRef=ObjectReference(apiVersion=null, fieldPath=null, kind=Pod, name=lcds-9a0c92bfe2c7fe9d584ed3d0a503808c-s01si, namespace=jfgosselin, resourceVersion=8071454, uid=ffb273f0-63df-11e6-bb9c-0050568e4d39, additionalProperties={}), additionalProperties={})], 
notReadyAddresses=[], ports=[EndpointPort(name=null, port=8888, protocol=TCP, additionalProperties={})], additionalProperties={})]`

**Comment by iocanel** [comment]
@jfgosselin: I'll have a look and I'll get back to you shortly.

**Comment by iocanel** [comment]
@jfgosselin: You are right! It doesn't handle correctly subsets with multiple addresses, which is a perfectly valid scenario.

**Comment by iocanel** [comment]
@jfgosselin: thanks for spotting and debugging :-)
