### ISSUE TITLE
Can't get a value from ConfigMap 

### ISSUE THREAD

**Issue by lburgazzoli** [fabric8io/spring-cloud-kubernetes#56]
I have a very simple sample that should retrieve a value from a ConfigMap but I can't get it working.

Code, pom and logs are on this gist: https://gist.github.com/lburgazzoli/c8cb1db8f57eeaeca57d8d5b53d61b1e

If I replace the home method with a direct call to a KubernetesClient, I'm able to get the desired value from the config map :

```java
@RestController
@SpringBootApplication
public class MyApplication {
    private static final Logger LOGGER = LoggerFactory.getLogger(MyApplication.class);

    @Autowired
    public KubernetesClient client;

    @RequestMapping("/")
    String home() {
        return client.configMaps().withName("demo").get().getData().get("mydata");
    }

    public static void main(String[] args) throws Exception {
        SpringApplication.run(MyApplication.class, args);
    }
}
```

It looks like the ConfigMap PropertySource is not taken into account.

**Comment by christian-posta** [comment]
@lburgazzoli Are you on OpenShift by chance? Or vanilla Kubernetes? so by default only the `default` service account is attached to a pod. this service account may not have privileges to read from the kubernetes API. 

If on open shift `oadm policy add-role-to-user <role> <username>`

see here https://docs.openshift.com/enterprise/3.2/admin_guide/manage_authorization_policy.html#viewing-cluster-policy

try adding 'edit' role to see if it works; then we can back it down from there

**Comment by lburgazzoli** [comment]
I'm on minikube and using the client with autowire in my app works as expected so it looks like something inhibits the PropertySource to load

**Comment by christian-posta** [comment]
@lburgazzoli what happens if you include this dependency?

```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-context</artifactId>
</dependency>
```

**Comment by lburgazzoli** [comment]
@christian-posta yep, that was the missing piece, thx.

So, should spring-cloud-context be declared non [optional](https://github.com/fabric8io/spring-cloud-kubernetes/blob/master/spring-cloud-kubernetes-core/pom.xml#L48) ?

**Comment by christian-posta** [comment]
yep @lburgazzoli looks like @iocanel fixed it on master. thanks for reporting this issue!
