### ISSUE TITLE
1) No implementation for io.fabric8.maven.core.util.GoalFinder was bound.

### ISSUE THREAD

**Issue by RobinsChens** [fabric8io/spring-cloud-kubernetes#70]
1) No implementation for io.fabric8.maven.core.util.GoalFinder was bound.

**Comment by iocanel** [comment]
This seems more like a https://github.com/fabric8io/fabric8-maven-plugin issue.

Can you please provide some more details on how you reproduce this?

**Comment by jstrachan** [comment]
this is a known issue of using the fabric8-maven-plugin with an older version of maven.
https://github.com/fabric8io/fabric8-maven-plugin/issues/556

if you use a more recent maven version (say 3.3.x) it should fix it
