### ISSUE TITLE
Docs mention adding role 'cluster-view' but role does not exist

### ISSUE THREAD

**Issue by donovanmuller** [fabric8io/spring-cloud-kubernetes#72]
Using OpenShift Origin 1.3.1 (minishift 0.9) and trying to add the `cluster-view` role to a service account [as per the docs](https://github.com/fabric8io/spring-cloud-kubernetes#service-account) but the `cluster-view` role doesn't exist:

```console
$ oc policy add-role-to-user cluster-view system:serviceaccount:...
Error from server: role "cluster-view" not found
```

According to the [OpenShift docs](https://docs.openshift.org/latest/admin_guide/manage_authorization_policy.html#viewing-cluster-policy), the role is called **`cluster-reader`**.

Not sure when this changed but the docs should be updated.
Happy to fix it, just confirming the above?

**Comment by iocanel** [comment]
I think that you are right!

@christian-posta: what do you think?

**Comment by christian-posta** [comment]
yah, you're right @donovanmuller 
wanna send a PR?
